### ISSUE TITLE
bug: Return invalid json

### ISSUE THREAD

**Issue by egut** [baslr/node-openweathermap#4]
Hi

Some times openwethermap seams to return invalid json and to fix that one need add a try/catch in the code.

```javascript
Uncaught exception [SyntaxError: Unexpected token i] SyntaxError: Unexpected token i
   at Object.parse (native)
     at IncomingMessage.<anonymous> (/srv/node_modules/openweathermap/openweather.js:120:21)
     at IncomingMessage.emit (events.js:117:20)
     at _stream_readable.js:938:16
     at process._tickCallback (node.js:419:13)
```

I'm not that good at coffee script but I recon that something like this should fix it

```javascript
getWeather = (opts, cb) ->
  http.get opts, (res) ->
    buffer = ''

    res.on 'data', (data) -> buffer += data;

    res.on 'end', () ->
      try
        json = JSON.parse buffer
        json.list = [] if ! json.list?
        cb json
      catch err
        cb err

```

**Comment by baslr** [comment]
Hi, thanks for the report.
I will look into it and provide an updated npm package in a few hours.

**Comment by egut** [comment]
Awesome!
